"""Add unique constraint to scrobbles

Revision ID: 246f1f042370
Revises: 
Create Date: 2025-04-05 20:25:39.880263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '246f1f042370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lastfm_username', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastfm_username'), 'users', ['lastfm_username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Create scrobbles table
    op.create_table('scrobbles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('artist', sa.String(), nullable=False),
        sa.Column('album', sa.String(), nullable=True),
        sa.Column('track', sa.String(), nullable=False),
        sa.Column('listened_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'artist', 'track', 'listened_at', name='uix_scrobble_user_track_time')
    )
    op.create_index(op.f('ix_scrobbles_id'), 'scrobbles', ['id'], unique=False)
    op.create_index(op.f('ix_scrobbles_artist'), 'scrobbles', ['artist'], unique=False)
    op.create_index(op.f('ix_scrobbles_listened_at'), 'scrobbles', ['listened_at'], unique=False)
    
    # Create artist_trends table
    op.create_table('artist_trends',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('period', sa.String(), nullable=False),
        sa.Column('artist', sa.String(), nullable=False),
        sa.Column('play_count', sa.Integer(), nullable=False),
        sa.Column('is_new_discovery', sa.Boolean(), default=False, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_trends_id'), 'artist_trends', ['id'], unique=False)
    op.create_index(op.f('ix_artist_trends_period'), 'artist_trends', ['period'], unique=False)
    op.create_index(op.f('ix_artist_trends_artist'), 'artist_trends', ['artist'], unique=False)
    
    # Create listening_activities table
    op.create_table('listening_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('track_count', sa.Integer(), nullable=False),
        sa.Column('listening_time', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listening_activities_id'), 'listening_activities', ['id'], unique=False)
    op.create_index(op.f('ix_listening_activities_date'), 'listening_activities', ['date'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening_activities')
    op.drop_table('artist_trends')
    op.drop_table('scrobbles')
    op.drop_table('users')
    # ### end Alembic commands ###
